name: Pull request

on: [pull_request]

jobs:
  #Step 1: Build Android Project
  #build:
  #name: Build
  #runs-on: ubuntu-latest

  #steps:
  #- uses: actions/checkout@v2
  #- name: set up JDK 1.8
  # uses: actions/setup-java@v1
  #with:
  # java-version: 1.8
  #- name: Build with Gradle
  # run: ./gradlew build

  #Step 2: Run Unit Testcase
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  #Step 3: Run Danger
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - uses: MeilCli/danger-action@v2
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}
